# Backstage override configuration for your local development environment

integrations:
  terraform:
    token: TOKEN_HERE

  unleash:
    url: UNLEASH_URL
    apiToken: UNLEASH_API_TOKEN
    numEnvs: 4
    # List of environments where flags and strategies can be edited
    # If not specified or empty, all environments are readonly
    editableEnvs:
      - development
      - staging
      # - production
    # By default, permissions are enabled which will limit feature
    # flag management users in the component owners group. If you
    # want anyone to be able to control flags, set to false
    enablePermissions: false
